'use strict';

const fs = require('fs');
const path = require('path');

/**
 * monitor-command: Generate macOS .command scripts for SSH-based remote monitoring
 *
 * Produces a bash script that SSH-es into a remote trading server
 * and displays live trading status (regime, signals, positions, balance).
 */

/**
 * Generate a monitor.command bash script for macOS (double-click to run)
 * @param {Object} config
 * @param {string} config.host       SSH target host (default: localhost)
 * @param {number} config.port       SSH port (default: 2222)
 * @param {string} config.user       SSH username
 * @param {string} config.monitorScript Remote Python script path
 * @param {string} config.python     Remote Python interpreter path
 * @param {number} config.interval   Refresh interval in seconds (default: 30)
 * @param {string} config.outputPath Where to write the .command file
 * @param {string} config.title      Terminal window title
 */
function generateMonitorCommand(config = {}) {
  const {
    host = 'localhost',
    port = 2222,
    user = 'pc_heisi_claude',
    monitorScript = '/home/pc_heisi_claude/trading/monitor.py',
    python = '/home/pc_heisi_claude/trading-env/bin/python3',
    interval = 30,
    outputPath = './lab/monitor.command',
    title = 'Auto-Trading Monitor',
  } = config;

  const script = `#!/bin/bash
# =============================================================
# Auto-Trading 实盘监控
# 双击即可打开终端，SSH 到 Nitro 每 ${interval} 秒刷新一次
# Generated by monitor-command skill (GEP)
# =============================================================

NITRO_HOST="${host}"
NITRO_PORT=${port}
NITRO_USER="${user}"
MONITOR_SCRIPT="${monitorScript}"
PYTHON="${python}"
INTERVAL=${interval}

# 窗口标题
printf '\\033]0;${title}\\007'

while true; do
    # 清屏
    printf '\\033[H\\033[J'

    # SSH 到 Nitro 执行监控脚本
    ssh -p "\${NITRO_PORT}" "\${NITRO_USER}@\${NITRO_HOST}" \\
        "\${PYTHON} \${MONITOR_SCRIPT}" 2>/dev/null

    # SSH 失败时显示错误
    if [ $? -ne 0 ]; then
        echo ""
        echo "  ⚠ SSH 连接失败（\${NITRO_USER}@\${NITRO_HOST}:\${NITRO_PORT}）"
        echo "  检查 Nitro 是否开机 / SSH 端口是否开放"
        echo ""
    fi

    echo ""
    echo "  \${INTERVAL}秒后刷新... (Ctrl+C 退出)"
    sleep "\${INTERVAL}"
done
`;

  const outPath = path.resolve(outputPath);
  const dir = path.dirname(outPath);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(outPath, script, { encoding: 'utf8', mode: 0o755 });
  console.log(`Generated: ${outPath}`);
  return { outputPath: outPath, host, port, user, interval };
}

function main(config = {}) {
  return new Promise((resolve) => {
    const result = generateMonitorCommand(config);
    resolve(result);
  });
}

module.exports = { generateMonitorCommand, main };

if (require.main === module) {
  const args = process.argv.slice(2);
  const cfg = {};
  for (let i = 0; i < args.length; i += 2) {
    const key = args[i].replace(/^--/, '');
    cfg[key] = args[i + 1];
  }
  generateMonitorCommand(cfg);
}
